openapi: 3.0.3
info:
  title: OpenAPI schema for Velero template .
components:
  schemas:
    variables:
      type: object
      properties:
        namespace_name:
          title: Namespace Name
          type: string
          description: The name of the Kubernetes namespace.
          default: velero
          x-walrus-ui:
            group: Basic
            order: 1
        chart_version:
          title: Chart Version
          type: string
          description: The version of the Velero Helm release chart.
          default: 7.2.1
          x-walrus-ui:
            group: Basic
            order: 2
        velero_schedule:
          title: Velero Schedule
          type: string
          description: The cron schedule for Velero backups
          default: '@every 24h'
          x-walrus-ui:
            group: Basic
            order: 3
        velero_schedule_ttl:
          title: Velero Schedule Ttl
          type: string
          description: Velero backups TTL
          default: 168h0m0s
          x-walrus-ui:
            group: Basic
            order: 4
        velero_image:
          title: Velero Image
          type: string
          description: The image for Velero provider
          default: velero/velero-plugin-for-aws:v1.10.0
          x-walrus-ui:
            group: Basic
            order: 5
        velero_provider:
          title: Velero Provider
          type: string
          description: Velero provider
          default: velero.io/aws
          x-walrus-ui:
            group: Basic
            order: 6
        velero_bucket:
          title: Velero Bucket
          type: string
          description: Bucket name
          default: dev-backup
          x-walrus-ui:
            group: Basic
            order: 7
        s3url:
          title: S3url
          type: string
          description: s3Url FQDN name
          default: https://minio.domainname.com
          x-walrus-ui:
            group: Basic
            order: 8
        aws_access_key_id:
          title: Aws Access Key Id
          type: string
          description: AWS Access Key ID
          default: ""
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 9
        aws_secret_access_key:
          title: Aws Secret Access Key
          type: string
          description: AWS Secret Access Key
          default: ""
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 10
        resources:
          title: Resources
          type: object
          description: Resource limits and requests for Velero Helm release.
          default:
            limits:
              cpu: 2000m
              memory: 4000Mi
            requests:
              cpu: 1000m
              memory: 2000Mi
          additionalProperties:
            additionalProperties:
              type: string
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 11
      x-walrus-ui:
        groupOrder:
        - Basic
