name: Terratest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terratest:
    strategy:
      matrix:
        engine: ["opentofu", "terraform"]
        version: ["1.8"]
        experimental: [false]
        include:
          - version: "1.8"
            engine: "opentofu"
            experimental: true
          - version: "1.8"
            engine: "terraform"
            experimental: false

    continue-on-error: ${{ matrix.experimental }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v1
        with:
          cluster-name: test-cluster

      - name: Verify kind cluster
        run: kubectl get nodes
        env:
          KUBECONFIG: ${{ steps.kind.outputs.kubeconfig-path }}

      - name: Ensure kubeconfig default location
        run: mkdir -p ~/.kube && cp ${{ steps.kind.outputs.kubeconfig-path }} ~/.kube/config && chmod 600 ~/.kube/config

      - name: Set KUBERNETES_MASTER
        run: export KUBERNETES_MASTER=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}') && echo "KUBERNETES_MASTER=$KUBERNETES_MASTER" >> $GITHUB_ENV

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        if: ${{ matrix.engine == 'terraform' }}
        with:
          terraform_version: ${{ matrix.version }}
          terraform_wrapper: false

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        if: ${{ matrix.engine == 'opentofu' }}
        with:
          tofu_version: ${{ matrix.version }}
          tofu_wrapper: false

      - name: Debug Kubernetes configuration
        run: echo "KUBECONFIG=${KUBECONFIG}" && cat ~/.kube/config && kubectl config view
        env:
          KUBECONFIG: ${{ steps.kind.outputs.kubeconfig-path }}

      - name: Run Terratest
        run: make terratest TERRAFORM_ENGINE=${{matrix.engine}}
        env:
          KUBECONFIG: ${{ steps.kind.outputs.kubeconfig-path }}
          KUBERNETES_MASTER: ${{ env.KUBERNETES_MASTER }}