name: Terratest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terratest:
    strategy:
      matrix:
        engine: ["opentofu", "terraform"]
        version: ["1.8"]
        experimental: [false]
        include:
          - version: "1.8"
            engine: "opentofu"
            experimental: true
          - version: "1.8"
            engine: "terraform"
            experimental: false

    continue-on-error: ${{ matrix.experimental }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        if: ${{ matrix.engine == 'terraform' }}
        with:
          terraform_version: ${{ matrix.version }}
          terraform_wrapper: false

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        if: ${{ matrix.engine == 'opentofu' }}
        with:
          tofu_version: ${{ matrix.version }}
          tofu_wrapper: false

      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create Kind Cluster
        run: kind create cluster --name test-cluster
  
      - name: Configure Environment for Kubernetes
        run: |
          export KUBECONFIG="$(kind get kubeconfig --name=test-cluster)"
          echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_ENV
          echo "KUBERNETES_MASTER=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}')" >> $GITHUB_ENV

      - name: Verify Kubernetes Cluster
        run: kubectl cluster-info
  
      - name: Run Terratest
        env:
          KUBECONFIG: ${{ env.KUBECONFIG }}
          KUBERNETES_MASTER: ${{ env.KUBERNETES_MASTER }}
        run: make terratest TERRAFORM_ENGINE=${{matrix.engine}}
  
      - name: Delete Kind Cluster
        if: always()
        run: kind delete cluster --name test-cluster